import { hashValue } from "@resilireplay/core";
import { AdapterTemplateSchema, parseAdapterTemplate, type AdapterTemplate } from "./contracts.js";

const OWNER = {
  repository: "aliengineering-byte/resilireplay",
  version: "0.6.0",
} as const;

const templates: readonly AdapterTemplate[] = [
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "tool-error",
    name: "Tool Error Recovery",
    description:
      "Injects one deterministic tool error and verifies the declared recovery boundary.",
    framework: "universal",
    frameworkVersionRange: ">=0.6",
    compatibility: "verified",
    safetyClass: "safe",
    mode: "campaign",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["tool.start", "tool.error", "recovery.decision", "recovery.result"],
    scenarioFixture: {
      fault: "tool-error",
      event: "tool.start",
      occurrence: 1,
      recovery: "retry",
      seed: 8,
      assertions: { outcome: "passed", noDuplicateSideEffects: true },
    },
    schemaValidation: { requiredEvidenceFields: ["tool.error", "recovery.result"] },
    limitations: ["Requires an adapter with an executable tool error boundary."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "duplicated-call",
    name: "Duplicated Tool Call",
    description:
      "Duplicates one tool request and verifies side-effect identity blocks double application.",
    framework: "universal",
    frameworkVersionRange: ">=0.6",
    compatibility: "supported",
    safetyClass: "unsafe",
    mode: "campaign",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["tool.start", "stream.duplicate", "guardrail.fail", "recovery.result"],
    scenarioFixture: {
      fault: "duplicated-call",
      event: "tool.start",
      occurrence: 1,
      recovery: "none",
      seed: 18,
      assertions: { outcome: "failed", noDuplicateSideEffects: true },
    },
    schemaValidation: { requiredEvidenceFields: ["tool.start", "stream.duplicate"] },
    limitations: ["Requires stable call identity before any external side effect."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "stream-corruption",
    name: "Stream Corruption",
    description:
      "Corrupts stream ordering and requires explicit missing, duplicate, or out-of-order evidence.",
    framework: "universal",
    frameworkVersionRange: ">=0.6",
    compatibility: "supported",
    safetyClass: "safe",
    mode: "campaign",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["stream.chunk", "stream.outOfOrder", "stream.missing", "run.error"],
    scenarioFixture: {
      fault: "stream-corruption",
      event: "stream.chunk",
      occurrence: 2,
      recovery: "none",
      seed: 28,
      assertions: { outcome: "failed", safetyPolicyCompliance: true },
    },
    schemaValidation: { requiredEvidenceFields: ["stream.chunk", "stream.outOfOrder"] },
    limitations: ["Requires stable stream item and sequence identity."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "tool-timeout",
    name: "Tool Timeout Recovery",
    description: "Injects a bounded one-shot tool timeout and expects a retry-safe outcome.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "verified",
    safetyClass: "safe",
    mode: "campaign",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["tool.timeout", "model.retry", "recovery.result", "guardrail.pass"],
    scenarioFixture: {
      fault: "tool-timeout",
      event: "tool.result",
      occurrence: 1,
      recovery: "retry",
      seed: 42,
      assertions: {
        outcome: "passed",
        noDuplicateSideEffects: true,
      },
    },
    schemaValidation: { requiredEvidenceFields: ["tool.timeout", "recovery.result"] },
    limitations: [
      "Does not execute remote tools.",
      "Requires deterministic trace fixture support.",
    ],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "rate-limit-retry",
    name: "Rate-Limit Recovery With Bounded Retry",
    description:
      "Injects an explicit rate-limit boundary and verifies bounded retry budget behavior.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "supported",
    safetyClass: "safe",
    mode: "campaign",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["model.error", "model.retry", "recovery.result"],
    scenarioFixture: {
      fault: "rate-limit",
      event: "model.request",
      occurrence: 1,
      recovery: "retry",
      seed: 101,
      assertions: {
        outcome: "passed",
        maxRetries: 2,
      },
    },
    schemaValidation: { requiredEvidenceFields: ["model.error", "model.retry", "recovery.result"] },
    limitations: ["May require a deterministic transport stub to avoid real rate-limit traffic."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "malformed-tool-result",
    name: "Malformed Tool Result Boundary",
    description:
      "Injects malformed tool output and verifies guarded replay to a known safe failure.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "verified",
    safetyClass: "unsafe",
    mode: "fixture",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["tool.result", "guardrail.fail", "run.error"],
    scenarioFixture: {
      fault: "malformed-tool-output",
      event: "tool.result",
      occurrence: 1,
      recovery: "none",
      seed: 11,
      assertions: {
        outcome: "failed",
        safetyPolicyCompliance: true,
      },
    },
    schemaValidation: { requiredEvidenceFields: ["tool.result", "guardrail.fail"] },
    limitations: ["Only valid on adapters that expose parsed tool payload boundaries."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "dropped-response",
    name: "Dropped Tool Response",
    description: "Drops a tool result event and expects recovery to avoid duplicate side effects.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "experimental",
    safetyClass: "safe",
    mode: "fixture",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["tool.start", "tool.retry", "partial.completion", "recovery.result"],
    scenarioFixture: {
      fault: "dropped-response",
      event: "tool.result",
      occurrence: 1,
      recovery: "retry",
      seed: 19,
      assertions: {
        outcome: "passed",
        noDuplicateSideEffects: true,
      },
    },
    schemaValidation: { requiredEvidenceFields: ["tool.start", "tool.retry", "recovery.result"] },
    limitations: ["Experimental until partial completion recovery is enabled in adapters."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "truncated-stream",
    name: "Truncated Stream Chunk Evidence",
    description:
      "Injects truncated stream chunks and validates explicit completion or truncation boundaries.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "supported",
    safetyClass: "safe",
    mode: "fixture",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["stream.truncated", "stream.completed", "stream.chunk"],
    scenarioFixture: {
      fault: "stream-truncation",
      event: "stream.chunk",
      occurrence: 1,
      recovery: "none",
      seed: 2026,
      assertions: {
        outcome: "failed",
        safetyPolicyCompliance: true,
      },
    },
    schemaValidation: { requiredEvidenceFields: ["stream.truncated", "stream.completed"] },
    limitations: ["Requires streaming-aware framework adapters or OTLP bridge input."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "duplicate-retry-prevention",
    name: "Duplicate Retry Prevention",
    description:
      "Injects a failed action then replay tries the same unsafe boundary twice to assert guardrails block it.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "verified",
    safetyClass: "unsafe",
    mode: "scenario",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["tool.start", "tool.retry", "partial.completion", "recovery.decision"],
    scenarioFixture: {
      fault: "tool-retry-replay",
      event: "tool.result",
      occurrence: 1,
      recovery: "retry",
      seed: 303,
      assertions: {
        outcome: "failed",
        noDuplicateSideEffects: true,
      },
    },
    schemaValidation: { requiredEvidenceFields: ["tool.start", "tool.retry", "recovery.decision"] },
    limitations: ["Requires deterministic unsafe-call classification in framework adapter."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "partial-completion-recovery",
    name: "Partial-Completion Recovery",
    description:
      "Creates a known partial completion and verifies no duplicate external side effects on retry.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "supported",
    safetyClass: "unsafe",
    mode: "scenario",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["partial.completion", "recovery.result", "recovery.decision"],
    scenarioFixture: {
      fault: "partial-completion",
      event: "tool.result",
      occurrence: 1,
      recovery: "retry",
      seed: 404,
      assertions: {
        outcome: "passed",
        noDuplicateSideEffects: true,
      },
    },
    schemaValidation: { requiredEvidenceFields: ["partial.completion", "recovery.result"] },
    limitations: ["Replay harness must model operation idempotency."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "handoff-failure",
    name: "Multi-Agent Handoff Failure",
    description:
      "Injects handoff routing failure and verifies failure does not corrupt sibling agent state.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "experimental",
    safetyClass: "unsafe",
    mode: "campaign",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["handoff.requested", "handoff.failed", "state.rollback", "recovery.result"],
    scenarioFixture: {
      fault: "handoff-failure",
      event: "handoff.requested",
      occurrence: 1,
      recovery: "retry",
      seed: 505,
      assertions: {
        outcome: "failed",
        noDuplicateSideEffects: true,
      },
    },
    schemaValidation: { requiredEvidenceFields: ["handoff.requested", "handoff.failed"] },
    limitations: ["Not all adapters expose full handoff topology today."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "context-corruption",
    name: "Context Corruption Boundary",
    description:
      "Injects an explicit checkpoint/context corruption boundary and validates deterministic rollback.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "documented",
    safetyClass: "unsafe",
    mode: "scenario",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: [
      "checkpoint.write",
      "checkpoint.resume",
      "state.rollback",
      "recovery.result",
    ],
    scenarioFixture: {
      fault: "checkpoint-corruption",
      event: "checkpoint.write",
      occurrence: 1,
      recovery: "retry",
      seed: 606,
      assertions: {
        outcome: "passed",
      },
    },
    schemaValidation: {
      requiredEvidenceFields: ["checkpoint.write", "state.rollback", "checkpoint.resume"],
    },
    limitations: ["Requires explicit checkpointed state support in the adapter."],
  },
  {
    schemaVersion: "resilireplay.adapter-template/v1.0.0",
    templateVersion: "1.0",
    id: "guardrail-failure",
    name: "Guardrail Blocked Decision",
    description:
      "Injects unsafe payload to trigger guardrail failure and confirms no unsafe recovery path.",
    framework: "universal",
    frameworkVersionRange: ">=5.0",
    compatibility: "verified",
    safetyClass: "unsafe",
    mode: "fixture",
    source: OWNER,
    license: "Apache-2.0",
    expectedEvidence: ["guardrail.start", "guardrail.fail", "run.error"],
    scenarioFixture: {
      fault: "guardrail-failure",
      event: "model.request",
      occurrence: 1,
      recovery: "none",
      seed: 707,
      assertions: {
        outcome: "failed",
        safetyPolicyCompliance: false,
      },
    },
    schemaValidation: {
      requiredEvidenceFields: ["guardrail.start", "guardrail.fail", "run.error"],
    },
    limitations: ["Safe for deterministic fixtures only."],
  },
];

const manifest = AdapterTemplateSchema.array().parse([...templates]);

export function adapterTemplates(): AdapterTemplate[] {
  return manifest.map((entry) => ({ ...entry }));
}

export function templateById(id: string): AdapterTemplate | undefined {
  const candidate = manifest.find((entry) => entry.id === id);
  return candidate ? { ...candidate } : undefined;
}

export function renderTemplateArtifact(
  template: AdapterTemplate,
  outputFileName = "template.json",
): string {
  const parsed = parseAdapterTemplate(template);
  const manifestDigest = hashValue(parsed);
  return JSON.stringify(
    {
      schemaVersion: "1.0",
      id: parsed.id,
      templateVersion: parsed.templateVersion,
      templateDigest: manifestDigest,
      generatedAt: new Date().toISOString(),
      outputFileName,
      source: parsed.source,
      license: parsed.license,
      mode: parsed.mode,
      data: parsed.scenarioFixture,
      expectedEvidence: parsed.expectedEvidence,
    },
    null,
    2,
  );
}
